Repository TradeWebProject/trade_web_project_FE, pull requests merged in 2024-06, with the labels that each got.

#2 [ setting ] 기본 셋팅
  tradeweb/.gitignore
  tradeweb/README.md
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/public/favicon.ico
  tradeweb/public/index.html
  tradeweb/public/logo192.png
  tradeweb/public/logo512.png
  tradeweb/public/manifest.json
  tradeweb/public/robots.txt
  tradeweb/src/App.css
  tradeweb/src/App.js
  tradeweb/src/App.test.js
  tradeweb/src/index.css
  tradeweb/src/index.js
  tradeweb/src/logo.svg
  tradeweb/src/reportWebVitals.js
  tradeweb/src/setupTests.js
Labels: setting

#4 라우터 세팅및 프로젝트 폴더 구조 생성
  package-lock.json
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/App.js
  tradeweb/src/components/common/AppLayout.js
  tradeweb/src/index.js
  tradeweb/src/pages/myPage/MyPage.js
Labels: setting

#7 [feature] nav바 UI 구현
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/assets/search.svg
  tradeweb/src/components/common/AppLayout.js
  tradeweb/src/components/nav/Nav.js
Labels: design, feat

#8 [ style ] 메인 서브컬러 theme 구현,로그인, 회원가입, 상세페이지 UI틀구현
  tradeweb/src/App.js
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/userAccount/InputField.js
  tradeweb/src/components/userAccount/Login.js
  tradeweb/src/components/userAccount/Signup.js
  tradeweb/src/pages/detail/DetailedPage.js
  tradeweb/src/pages/signIn/LoginPage.js
  tradeweb/src/styles/theme.js
Labels: design, feat

#10 마이페이지 레이아웃 작업 및 상품 등록 페이지 레이아웃 작업 진행
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/App.js
  tradeweb/src/pages/myPage/MyPage.js
  tradeweb/src/pages/productWritePage/ProductWritePage.js
Labels: design

#12 [ design ] Footer UI 구현
  tradeweb/src/components/common/AppLayout.js
  tradeweb/src/components/footer/Footer.js
Labels: design

#14 상품 등록페이지 UI 작업 진행 및 마이페이지 불필요한 코드 삭제
  tradeweb/src/assets/profile.svg
  tradeweb/src/pages/myPage/MyPage.js
  tradeweb/src/pages/productWritePage/ProductWritePage.js
Labels: design, fix

#18 마이페이지 - 결제내역 탭 UI 구조 작업 진행
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/pages/myPage/MyPage.js
Labels: design

#17 [ feat/fix/design ] theme전이랑 방식 통일, 채팅ui틀 구현, 드롭다운컴포넌트 구현, 상세페이지 ui 수정
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/App.js
  tradeweb/src/assets/heart.svg
  tradeweb/src/components/chatlist/ChatControl.js
  tradeweb/src/components/chatlist/ChatList.js
  tradeweb/src/components/chatlist/RemoteControl.js
  tradeweb/src/components/common/AppLayout.js
  tradeweb/src/components/common/DropdownOptions.js
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/userAccount/Login.js
  tradeweb/src/styles/theme.js
Labels: design, feat, fix

#20 상품 등록 페이지 판매 날짜, 카테고리, 옵션 UI 수정
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/components/common/DropdownOptions.js
  tradeweb/src/pages/myPage/MyPage.js
  tradeweb/src/pages/productWritePage/ProductWritePage.js
Labels: design, fix

#21 [feat] 검색 시 무한스크롤 기능 적용
  tradeweb/src/components/search/SearchContent.js
Labels: feat

#25 결제내역, 판매내역, 상품수정, 상품상세 페이지 댓글 목록 UI 작업 진행
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/App.js
  tradeweb/src/components/common/Modal/Modal.js
  tradeweb/src/components/common/Modal/ModalContainer.js
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/hooks/useClickOutside.js
  tradeweb/src/pages/myPage/MyPage.js
  tradeweb/src/pages/productDetailManagementPage/ProductDetailManagementPage.js
Labels: design, fix

#26 [ fix ] 무한스크롤 데이터 중복 출력 수정
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/dummyData.js
Labels: fix

#29 [ feature ] 클릭한 필터 결과 창에서 보일 수 있도록 기능 추가
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/SearchFilter.js
  tradeweb/src/components/search/SearchResult.js
Labels: feat

#30 [ design / fix ] 리뷰(후기) UI구현, 드롭다운 컴포넌트 수정, 채팅기능 수정
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/App.js
  tradeweb/src/components/chatlist/ChatList.js
  tradeweb/src/components/chatlist/MessageTime.js
  tradeweb/src/components/chatlist/RemoteControl.js
  tradeweb/src/components/common/DropdownOptions.js
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/review/Review.js
  tradeweb/src/components/review/SellerInfo.js
  tradeweb/src/pages/reviewPage/reviewPage.js
  tradeweb/src/styles/theme.js
Labels: design, fix

#32 상세페이지 댓글 목록 position 수정
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/assets/rightarrow.svg
  tradeweb/src/components/detail/Detail.js
Labels: design

#42 [fix / design / feature ]상품 상세페이지 리뷰 등록 UI 추가 및 옵션 드롭다운 리스트 삭제
  tradeweb/src/components/detail/Detail.js
Labels: design, fix

#45 상세페이지 찜하기 기능 구현
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/product/ProductRegister.js
  tradeweb/src/pages/productWritePage/ProductWritePage.js
Labels: fix

#55 [ feature/ fix] 마이페이지에 있는 탭 컴포넌트로 분리 (진행중)
  tradeweb/src/App.js
  tradeweb/src/components/myProductManagement/MyPageManagement.js
  tradeweb/src/components/product/ProductModify.js
  tradeweb/src/pages/myPage/MyPage.js
  tradeweb/src/pages/productDetailManagementPage/ProductDetailManagementPage.js
Labels: feat, fix

#49 [ design / fix] 채팅 ui 및 기능 수정 / 드롭다운 css 수정
  tradeweb/.env
  tradeweb/src/components/chatlist/ChatList.js
  tradeweb/src/components/common/DropdownOptions.js
  tradeweb/src/components/detail/Detail.js
Labels: design, fix

#58 [ feature ] 이미지 슬라이더 구현
  tradeweb/src/App.js
  tradeweb/src/assets/slideImg1.jpg
  tradeweb/src/assets/slideImg2.jpg
  tradeweb/src/assets/slideImg3.jpg
  tradeweb/src/components/main/ImageSlider.js
  tradeweb/src/components/main/ImageSliderData.js
  tradeweb/src/components/main/Main.js
  tradeweb/src/pages/main/MainPage.js
Labels: feat

#60 [ feat ] 로그인, 회원가입, 로그아웃 Axios요청 구현
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/components/userAccount/Login.js
Labels: feat

#61 [feature / fix] 상품등록 axios post 요청 기능 개발
  tradeweb/package-lock.json
  tradeweb/src/components/main/Main.js
  tradeweb/src/components/myProductManagement/MyPageManagement.js
  tradeweb/src/components/payment/UserPayment.js
  tradeweb/src/components/product/ProductRegister.js
  tradeweb/src/components/userAccount/MyProfile.js
Labels: feat, fix

#67 [ feat ] nav바에 로그인, 로그아웃, 회원가입 버튼 추가
  tradeweb/package-lock.json
  tradeweb/package.json
  tradeweb/src/components/nav/Nav.js
  tradeweb/src/components/userAccount/Login.js
Labels: feat

#68 [ feature ] 상품 목록 컴포넌트화
  tradeweb/src/components/search/ProductItem.js
  tradeweb/src/components/search/ProductList.js
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/SearchResult.js
Labels: feat, fix

#70 [ feature ] 메인 페이지 UI 수정
  tradeweb/src/components/main/ImageSlider.js
  tradeweb/src/components/main/Main.js
  tradeweb/src/components/search/ProductList.js
  tradeweb/src/components/search/SearchContent.js
Labels: feat, fix

#71 [feature / fix] 관리자 등록된 상품 목록 보여주는 기능 개발 및 판매완료된 상품목록 보여주는 기능 개발
  tradeweb/.env
  tradeweb/src/components/payment/UserProductSellHistory.js
Labels: feat, fix

#75 [feature / fix ] 관리자 상품 목록에서 상품명 클릭시 관리자 상품 상세 페이지로 이동 및 데이터 렌더링
  tradeweb/.env
  tradeweb/src/App.js
  tradeweb/src/components/payment/UserProductSellHistory.js
  tradeweb/src/components/product/ProductModify.js
Labels: feat, fix

#79 [ feature ] 검색 기능 구현
  tradeweb/src/App.js
  tradeweb/src/components/main/Main.js
  tradeweb/src/components/nav/Nav.js
  tradeweb/src/components/search/ProductItem.js
  tradeweb/src/components/search/ProductList.js
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/dummyData.js
Labels: feat, fix

#82 [fix ] 관리자 상품 등록시 로컬스트로지에서 토큰 정보 가져올 수 있도록 코드 수정
  tradeweb/src/components/product/ProductRegister.js
Labels: fix

#88 [ feat / design / refactor / fix ] 상세페이지 GET요청 구현 / 상세페이지, 리뷰페이지 디자인 수정 / 리뷰작성부분 리뷰페이지로 이동 / 로그인 userId 로컬스토리지 저장
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/review/Review.js
  tradeweb/src/components/review/SellerInfo.js
  tradeweb/src/components/userAccount/Login.js
Labels: design, feat, refactor, fix

#94 [ feature ] 검색 기능 필터 구현
  tradeweb/src/components/main/ImageSlider.js
  tradeweb/src/components/search/ProductItem.js
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/SearchFilter.js
  tradeweb/src/components/search/SearchResult.js
Labels: feat

#96 [ feat ] 리뷰조회 및 작성 기능 구현(채팅, 구매기능 구현후로 미루겠습니다)
  tradeweb/src/App.js
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/review/Review.js
Labels: feat

#99 [ fix ] 웹 에디터로 수정시에 발생한 오류 수정
  tradeweb/src/components/search/SearchContent.js
Labels: hotFix

#100 [ feat ] 회원가입시 관심사 등록기능 추가
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/userAccount/Login.js
Labels: feat

#103 [feat / fix ] 마이프로필 userId 로컬스토리지에서 가져올 수 있도록 수정 및 관심사 목록 조회
  tradeweb/src/components/userAccount/MyProfile.js
Labels: bug, feat, fix

#105 [feature / fix ] 마이프로필 관심사 여러개 수정 할 수 있도록 코드 수정
  tradeweb/src/components/userAccount/MyProfile.js
Labels: bug, fix

#106 [feature / fix ] 찜목록 조회 기능 개발 및 찜목록 컴포넌트 분리
  tradeweb/src/components/myProductManagement/MyPageManagement.js
  tradeweb/src/components/userAccount/MyProfile.js
  tradeweb/src/components/userAccount/MyWishList.js
Labels: feat, fix

#107 [ feature ] 검색 기능 오류 수정 #95
  tradeweb/src/components/main/Main.js
  tradeweb/src/components/nav/Nav.js
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/SearchFilter.js
Labels: feat, fix

#110 [ fix ] 회원가입 업로드 및 기능 fix
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/userAccount/InputField.js
Labels: fix

#111 마이프로필 이미지 미리보기 기능 추가 + 찜 목록 GET 요청 기능 구현
  tradeweb/src/components/userAccount/MyProfile.js
  tradeweb/src/components/userAccount/MyWishList.js
Labels: bug, feat, fix

#118 [ feature ] 메인페이지 유저 관심 상품 출력 #117
  tradeweb/src/components/main/Main.js
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/SearchFilter.js
  tradeweb/src/components/search/SearchResult.js
Labels: feat

#119 [ feature ] 메인페이지 관심상품 출력, login.js 수정
  tradeweb/src/components/main/Main.js
  tradeweb/src/components/nav/Nav.js
  tradeweb/src/components/search/ProductItem.js
  tradeweb/src/components/search/SearchContent.js
  tradeweb/src/components/search/SearchResult.js
  tradeweb/src/components/userAccount/Login.js
Labels: feat, fix

#127 [ fix, feat ] 구매문의 후 새로고침전까지 채팅목록이 생성되지 않던 오류 픽스, 행동없을시 로그아웃 기능추가
  tradeweb/src/App.js
  tradeweb/src/components/chatlist/ChatList.js
  tradeweb/src/components/detail/Detail.js
  tradeweb/src/components/nav/Nav.js
  tradeweb/src/components/userAccount/Login.js
  tradeweb/src/components/userAccount/useAutoLogoutOnInactivity.js
Labels: feat, fix

#128 [ fix ] searchResult 오류 수정
  tradeweb/src/components/search/SearchResult.js
Labels: hotFix

#129 [ fix ] split 에러 수정
  tradeweb/src/components/main/Main.js
Labels: hotFix

#130 [ fix ] 상단 타이틀 및 이미지 임시 수정
  tradeweb/public/favicon.ico
  tradeweb/public/index.html
Labels: fix

#131 [ fix ] mixed content 수정
  tradeweb/public/index.html
Labels: fix

#132 [ hotfix ] 검색 필터기능 오류 수정
  tradeweb/public/index.html
  tradeweb/src/components/search/SearchResult.js
Labels: hotFix

#133 [ fix ] 필터 제거 버튼 삭제
  tradeweb/src/components/search/SearchContent.js
Labels: fix
